require:
  - rubocop-performance
  - rubocop-rails

Metrics/LineLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Rails/Present:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/GlobalVars:
  Enabled: false

AllCops:
  Exclude:
    - node_modules/node-sass/src/libsass/contrib/*.spec
